### PR TITLE
Vs2017

### PR DESCRIPTION
**Pull request by milbrandt**
update solution to VS2017 (I know, there is VS2019 out since Tuesday) and update Fody Nuget.
This fixes also the question arised at [Stackoverflow](https://stackoverflow.com/questions/44470333/error-on-using-fody-implementpropertychanged) regarding 'ImplementPropertyChangedAttribute' is obsolete when Fody is updated.

Targeting .NET platform 4.5 has not been changed by intend.

### CODE REVIEW

**Comment by isaacabraham** [comment]
wow, thanks! will test this out locally and then merge. thanks!

**Comment by milbrandt** [comment]
ping

**Comment by isaacabraham** [comment]
Right. Doing this now. Nearly one year is unnacceptable!

**Comment by isaacabraham** [comment]
Thanks again for doing this. Next job would be to upgrade to netcore and / or net sdk ;-)

**Pull request merged**
